default: &default
  adapter: mysql2
  database: coursie
  encoding: utf8mb4
  username: root
  password: YourStrongPassword!
  host: localhost
  port: 3306

development:
  <<: *default
  database: finance

test:
  <<: *default

production:
  <<: *default
  
